apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME
  namespace: NS_Name
spec:
  selector:
    app: SERVICENAME
  ports:
    - port: 9600
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  name: SERVICENAME-ingress
  namespace: NS_Name
spec:
  rules:
    - host: SERVICENAME.exapmle.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
          - backend:
              service:
                name: SERVICENAME
                port:
                  number: 9600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICENAME
  namespace: NS_Name
  labels:
    app: SERVICENAME
spec:
  selector:
    matchLabels:
      app: SERVICENAME
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: SERVICENAME
    spec:
      containers:
        - image: Localrepo_URL/docker/NS_Name/SERVICENAME:0.0.1-SNAPSHOT
          name: SERVICENAME
          imagePullPolicy: Always
          ports:
            - containerPort: 9600
              name: SERVICENAME
          env:
            - name: SERVICENAME_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-host-secret
                  key: SERVICENAME-database-user
            - name: SERVICENAME_DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-host-secret
                  key: SERVICENAME-database-pass
            - name: SERVICENAME_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-host-secret
                  key: mysql-db-name
            - name: SERVICENAME_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: SERVICENAME-cm
                  key: SERVICENAME-database-host
            - name: SERVICENAME_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: SERVICENAME-cm
                  key: SERVICENAME-database-port
            - name: SERVICENAME_PORT
              valueFrom:
                configMapKeyRef:
                  name: SERVICENAME-cm
                  key: SERVICENAME-port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: SERVICENAME-cm
  namespace: NS_Name
  labels:
    app: SERVICENAME
data:
  SERVICENAME-database-host: "mysql-host"
  SERVICENAME-database-port: "3306"
  SERVICENAME-port: "9600"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-host-secret
  namespace: NS_Name
type: Opaque
data:
  mysql-root-password: base64 hashed password
  mysql-username: base64 hashed username
  mysql-password: base64 hashed password
  mysql-db-name: base64 hashed db-name
  SERVICENAME-database-user: base64 hashed database-user
  SERVICENAME-database-pass: base64 hashed database-pass