apiVersion: v1
kind: Secret
metadata:
  name: SERVICENAME-mysql-secret
  namespace: NS_Name
type: Opaque
data:
  mysql-root-password: base64 hashed password
  mysql-username: base64 hashed username
  mysql-password: base64 hashed password
  mysql-db-name: base64 hashed db-name
  SERVICENAME-database-user: base64 hashed database-user
  SERVICENAME-database-pass: base64 hashed database-pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: SERVICENAME-mysql-cm
  namespace: NS_Name
  labels:
    app: SERVICENAME
    app: mysql
data:
  my.cnf: |-
    [client]
    port   = 3306
    socket   = /var/run/mysqld/mysqld.sock
    default-character-set=utf8
    [mysql]
    default-character-set=utf8
    [mysqld_safe]
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    nice   = 0
    [mysqld]
    user   = mysql
    pid-file = /var/run/mysqld/mysqld.pid
    socket   = /var/run/mysqld/mysqld.sock
    port   = 3306
    basedir    = /usr
    datadir    = /var/lib/mysql
    tmpdir   = /tmp
    lc-messages-dir  = /usr/share/mysql
    explicit_defaults_for_timestamp
    collation-server = utf8_unicode_ci
    init-connect='SET NAMES utf8'
    character-set-server = utf8
    log-error  = /var/log/mysql/error.log
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    symbolic-links=0
    max_connections=4096
    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICENAME-mysql
  namespace: NS_Name
  labels:
    app: SERVICENAME
spec:
  selector:
    app: SERVICENAME
    tier: mysql
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICENAME-mysql
  namespace: NS_Name
  labels:
    app: SERVICENAME
spec:
  selector:
    matchLabels:
      app: SERVICENAME
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: SERVICENAME
        tier: mysql
    spec:
      containers:
      - image: artifactory.spng.ir/docker/mysql:5.6
        name: mysql
        securityContext:
          runAsUser: 2015
          allowPrivilegeEscalation: false
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SERVICENAME-mysql-secret 
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: SERVICENAME-mysql-secret
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: SERVICENAME-mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: SERVICENAME-mysql-secret
              key: mysql-db-name
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: SERVICENAME-mysql-persistent-storage
          mountPath: /var/lib/mysql
          readOnly: false
      volumes:
      - name: SERVICENAME-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: SERVICENAME-mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: SERVICENAME-mysql-pv-claim
  namespace: NS_Name
  labels:
    app: SERVICENAME
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
